settings:
  lib_name: dff_flat_new_limited_3
  debug: True
  debug_dir: debug_new_7
  simulation:
    backend: ngspice-shared
  units:
    time: ns
    voltage: V
    current: uA
    pulling_resistance: kOhm
    leakage_power: nW
    capacitive_load: pF
    energy: fJ
  named_nodes:
    primary_ground:
      name: VSS
      voltage: 0
    primary_power:
      name: VDD
      voltage: 1.8
  omit_on_failure: False

cells:
  dff_flat:
    netlist: "cells/dff_flat_pex_newest_2.spice"
    models: ["/foss/pdks/sky130A/libs.tech/ngspice/sky130.lib.spice tt"]
    area: 104.21975
    inputs: ['D']
    outputs: ['Q']
    clock: posedge CLK
    state: ["IQ = D"]
    functions: ["Q <= IQ"]
    data_slews: [1.0]
    clock_slews: [1.0]
    loads: [0.001]
    metastability_constraint_sweep_samples: 5

